using OpenCodeDev.NetCMS.Compiler.Core.Builder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace OpenCodeDev.NetCMS.Compiler.Cli
{
    public static class Commenter
    {
        public static CommentBuilder Info(){
            Version version = typeof(Commenter).Assembly.GetName().Version;
            CommentBuilder comment = new CommentBuilder();
            comment.AddLine($"-- GENERATED BY NetCMS-Cli v{version.Major}.{version.Minor}.{version.MajorRevision} BUILD {version.Revision} -- ");
            comment.AddLine($"Created on {DateTime.Now}");
            comment.AddLine($"Repos CLI: https://github.com/OpenCodeDev/OpenCodeDev.NetCMS.Compiler");
            comment.AddLine($"License: MIT");
            comment.AddLine($"Author: Max Samson");
            comment.AddLine($"Company: OpenCodeDev");
            return comment;
        }
    }
}
